### ISSUE TITLE
inTable does not work with internal FSharp record type

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/FSharp.Azure#6]
`inTable` does not work with internal FSharp record type, only public types. 

    System.Exception was unhandled
    Message: An unhandled exception of type 'System.Exception' occurred in mscorlib.dll
    Additional information: Type ConfigurationInsert must be either an ITableEntity or an F# record type

The code in `TableStorage.fs` 

    static member val CreateTableOperation = lazy (
        match typeof<'T> with
        | t when typeof<ITableEntity>.IsAssignableFrom t -> createTableOperationFromTableEntity
        | t when FSharpType.IsRecord t -> createTableOperationFromRecord
        | _ -> failwithf "Type %s must be either an ITableEntity or an F# record type" typeof<'T>.Name)

does not recognize the type as `FSharpType.IsRecord`.
				
I have short sample project.

**Comment by daniel-chambers** [comment]
Thanks for reporting this. It's weird that FSharpType.IsRecord would not identify internal record types... it's a built-in F# library function.

I'm currently away at a conference, but when I get back in a few days I'll take a look at this problem.

**Comment by dsyme** [comment]
You have to give a BindingFlags.Public ||| BindingFlags.NonPublic to the optional binding flags parameter for  FSharpType.IsRecord

**Comment by daniel-chambers** [comment]
That'd do it! Thanks @dsyme!  

I'll make a patch and a test for it and push a new nuget as I get a chance.

**Comment by daniel-chambers** [comment]
This has been fixed and released in v1.0.2

**Comment by jackfoxy** [comment]
v1.0.2 tested out good for me, thanks
